Development updating ubuntu flist
threefoldtech/grid_weblets pull request #1025
Opened 2022-09-21 14:33 UTC by zaelgohary

### Description

Editing Ubuntu22.04 flist in microVM

### Changes

ubuntu22.04 in microVM

### Related Issues

- https://github.com/threefoldtech/grid_weblets/issues/1017

2022-09-21 15:52 UTC, AhmedHanafy725 requested changes

2022-09-21 15:52 UTC, AhmedHanafy725 commented on src/elements/vm/Vm.wc.svelte
> +    { name: "Ubuntu-22.04", url: "https://hub.grid.tf/zaelgohary.3bot/threefolddev-ubuntu-22.04.flist", entryPoint: "/init.sh" },
wrong entrypoint?

2022-09-22 10:25 UTC, AhmedHanafy725 approved these changes

2022-09-22 10:26 UTC, zaelgohary commented on src/elements/vm/Vm.wc.svelte
> +    { name: "Ubuntu-22.04", url: "https://hub.grid.tf/zaelgohary.3bot/threefolddev-ubuntu-22.04.flist", entryPoint: "/init.sh" },
changed to /sbin/zinit init

2022-09-22 10:26 UTC, merged