Removed The envs tab and the mountpoint field from the disks tab
threefoldtech/grid_weblets pull request #1064
Opened 2022-10-25 15:59 UTC by maayarosama

### Description
Updated  full vm weblet solutiob

### Changes

Removed the Environment Variables tab and the Mount Point field from the Disks tab
### Related Issues

#1015

2022-10-27 12:56 UTC, AhmedHanafy725 requested changes

2022-10-30 13:12 UTC, maayarosama commented on src/elements/fullvm/Fullvm.wc.svelte
> +      console.log("data.envs[0]",data.envs[0]);
Done

2022-10-30 13:13 UTC, maayarosama commented on src/types/vm.ts
> +export class DiskFullVm {
The DiskFullvm is now defined in  the fullvm types.

2022-10-31 06:52 UTC, AhmedHanafy725 approved these changes

2022-10-31 07:59 UTC, merged