QVM weblet
threefoldtech/grid_weblets pull request #1102
Opened 2022-11-14 13:38 UTC by 0oM4R

### Description
As in #1071, VM with QSFS solution added to weblet

### Changes

- Add QVM  to 

> 1. App.vue
> 2. editor.vue
> 3. App.svelte
> 4. DeployedList.wc.svelte
> 5. currentDeployment.ts _with QSFS_
> 6. solutionsList.ts

- Create QSFS type 
- Create Qvm element
- Create DeployQvm
- Add QSFS to DeployVM.ts
- Add qsfsSisk to Vm type
- Add some validation in validateName.ts
- Add delete qsfs in deleteDeployment.ts
- Add metrics label to Table.svelte to use it in view qsfs metrics 
- use Multiselect element in selectNodeId.svelte
- modify MultiSelect.svelte layout
### Related Issues

List of related issues
#1071 
### Checklist

- [x] Build pass
- [x] Code format and docstrings

2022-11-14 13:44 UTC, xmonader requested changes
lgtm

2022-11-14 14:01 UTC, xmonader approved these changes

2022-11-15 08:09 UTC, AhmedHanafy725 requested changes

2022-11-15 08:09 UTC, AhmedHanafy725 commented on src/utils/deployQVM.ts
> +    projectName: `QSFS of vm ${vm.name}`,
that's too long for the project name, can't it be `QVM`?

2022-11-15 08:09 UTC, AhmedHanafy725 commented on src/utils/validateName.ts
> +  if (!value.length) return `zDB password is required`
```suggestion
  if (!value.length) return `ZDB password is required`
```

2022-11-15 08:09 UTC, AhmedHanafy725 commented on src/utils/validateName.ts
> +
```suggestion
  return "ZDB count must be a valid number.";
  else if(value < 3) return `Minimum allowed ZDB is 3 ZDBs`;
  
```

2022-11-15 08:09 UTC, AhmedHanafy725 commented on src/elements/DeployedList/DeployedList.wc.svelte
> +            const domain = rows[i].details.mounts[0]["metricsEndpoint"];
this endpoint is only available on the planetary network, should it be exposed over the gateway? @xmonader

2022-11-15 08:09 UTC, AhmedHanafy725 commented on src/elements/qvm/Qvm.wc.svelte
> +      placeholder: "Memory of each ZDB in MB",
this is confusing, is it disk or memory?

2022-11-15 13:59 UTC, 0oM4R commented on src/elements/qvm/Qvm.wc.svelte
> +      placeholder: "Memory of each ZDB in MB",
resolved to be "Disk size"

2022-11-15 15:18 UTC, AhmedHanafy725 commented on src/elements/DeployedList/DeployedList.wc.svelte
> +            const domain = rows[i].details.mounts[0]["metricsEndpoint"];
let's remove this button for the metrics endpoint, and just keep it in the deployment details

2022-11-16 08:19 UTC, AhmedHanafy725 commented on src/elements/qvm/Qvm.wc.svelte
> +      placeholder: "Disk size of each ZDB in MB",
disk size in all weblets is in GB, can you convert it to be consistent?

2022-11-16 16:08 UTC, AhmedHanafy725 approved these changes

2022-11-16 16:08 UTC, merged