Fix profile manager not working
threefoldtech/grid_weblets pull request #1172
Opened 2022-12-18 16:17 UTC by MohamedElmdary

2022-12-18 16:32 UTC, xmonader approved these changes

2022-12-18 17:59 UTC, Omarabdul3ziz approved these changes

2022-12-18 19:47 UTC, xmonader requested changes
Linting is failing

2022-12-19 09:00 UTC, Mahmoud-Emad approved these changes

2022-12-20 13:12 UTC, maayarosama commented
The node filter is broken. It requests the filters over the current running server rather than the gridproxy
```
http://localhost:8080/nodes?free_mru=8589934592&free_sru=53687091200&free_hru=&free_ips=&ipv4=&ipv6=&gateway=&farm_ids=&farm_name=&country=&city=&dedicated=&available_for=79&status=up&page=
 ```
Also the playground is broken on the development  mode. The profile manager button is broken and I can't switch between tabs.

2022-12-21 11:18 UTC, maayarosama commented
Deploy button isn't enabled even if all the required fields are filled.
![deploy btn](https://user-images.githubusercontent.com/66883096/208891986-32dab393-972c-4ca0-ac09-84ceeb206f5e.png)

And in the development mode, The profile manager button is fixed. However the tabs are still broken and I can't switch between them.
![Peek 2022-12-21 13-16](https://user-images.githubusercontent.com/66883096/208892926-0ecb50f0-4df0-40c8-96f2-079eed4fa05f.gif)

2022-12-21 12:47 UTC, maayarosama approved these changes

2022-12-21 14:18 UTC, xmonader approved these changes

2022-12-21 14:26 UTC, merged