Fixing error message
threefoldtech/grid_weblets pull request #1236
Opened 2023-01-10 13:31 UTC by zaelgohary

### Description

Fixing error message in VM & Full VM

### Changes

Fixing error message in VM & Full VM

### Related Issues

- https://github.com/threefoldtech/grid_weblets/issues/1224

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2023-01-11 11:31 UTC, xmonader requested changes
we can create a function e.g normalizeErrorMessage that can be used in all of these files maybe?

2023-01-11 11:49 UTC, xmonader commented on src/utils/deploymentErrMsg.ts
> +    : `Falied to deploy ${type}.`;
Failed instead of Falied

2023-01-11 11:49 UTC, xmonader commented on src/utils/deploymentErrMsg.ts
> +function deploymentErrMsg(err: string, type: string) {
please make it `normalizeDeploymentErrorMessage`

2023-01-12 11:43 UTC, MohamedElmdary approved these changes

2023-01-12 11:51 UTC, xmonader approved these changes

2023-01-12 11:51 UTC, merged