Remove null values from nodeId Filters
threefoldtech/grid_weblets pull request #1331
Opened 2023-02-27 09:18 UTC by MohamedElmdary

## Issues
- https://github.com/threefoldtech/grid_weblets/issues/1279

2023-02-27 10:34 UTC, Mahmoud-Emad commented
The issue still there, i tried the scenario mentioned in the issue and seems the issue are still there.

2023-03-01 07:31 UTC, zaelgohary reviewed
Issue is still there.

![image](https://user-images.githubusercontent.com/40770501/222072968-92d8a6f3-d019-46b4-a2d9-ffe7010322bd.png)

2023-03-08 11:26 UTC, zaelgohary requested changes

2023-03-08 11:26 UTC, zaelgohary commented on src/components/SelectNodeId.svelte
> +    // nodeIdSelectField.options[0].label = "Loading...";
Can you remove this comment?

2023-03-08 11:44 UTC, Mahmoud-Emad requested changes

2023-03-08 11:44 UTC, Mahmoud-Emad commented on src/components/SelectNodeId.svelte
> +      {typeof filters[field.symbol]}
Remove those tow lines please if not needed :)

2023-03-08 12:05 UTC, Mahmoud-Emad approved these changes

2023-03-08 13:03 UTC, zaelgohary approved these changes

2023-03-08 13:05 UTC, merged