Update warning messages
threefoldtech/grid_weblets pull request #1344
Opened 2023-03-01 12:09 UTC by MohamedElmdary

![image](https://user-images.githubusercontent.com/31689104/222135406-98379bed-5d71-46ca-b885-218704c3c587.png)
![image](https://user-images.githubusercontent.com/31689104/222135431-173393c7-7ec2-47ff-851a-d089c51e5e83.png)

2023-03-01 13:26 UTC, xmonader approved these changes

2023-03-01 13:27 UTC, xmonader commented
Will leave it for @robvanmieghem to approve and merge, also i noticed the action type deleting/creating isn't there, I believe what was there is "deployment.type"

2023-03-02 09:51 UTC, robvanmieghem commented
Not quite ideal in the case of a deployment apparantly "action FullVM" is not a proper sentence

2023-03-02 12:50 UTC, zaelgohary approved these changes

2023-03-08 10:58 UTC, xmonader requested changes
check @robvanmieghem 's comment please

2023-03-08 15:55 UTC, xmonader approved these changes

2023-03-08 15:57 UTC, AhmedHanafy725 approved these changes

2023-03-08 15:59 UTC, merged