Development fix cypress tests
threefoldtech/grid_weblets pull request #1425
Opened 2023-04-03 13:03 UTC by A-Harby

### Description

- Updating cypress tests with new changes in profile manager and MicroVM.
- Fixing old paths
- Fixing workflow and adding environment variable secrets.

2023-04-03 13:09 UTC, A-Harby commented
Tested the workflow and was successfully pass in https://github.com/threefoldtech/grid_weblets/actions/runs/4596976272/jobs/8119102083

2023-04-04 08:10 UTC, mohamedamer453 requested changes
- Lastly the [`baseUrl`](https://github.com/threefoldtech/grid_weblets/blob/development/cypress.config.ts#L5) in `cypress.config.ts` should be updated to `play.dev.grid.tf`

- Other than the mentioned comments for the ssh key and the configuration everything ran fine without any issues.

   - Locally
      - Headed Mode 
      
         ![image](https://user-images.githubusercontent.com/101194226/229727012-3c8a25ad-84f4-47cd-952b-eac0131b692d.png)

      - Headless Mode

        ![image](https://user-images.githubusercontent.com/101194226/229729015-2a0922cc-6ac3-40e9-b9b6-e1a22ac53c74.png)

   - Workflow
   
       https://github.com/threefoldtech/grid_weblets/actions/runs/4605016629#summary-12499479806

2023-04-04 08:10 UTC, mohamedamer453 commented on cypress/fixtures/credentials.json
> +  "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvmSYj5BKWkizdNyIziMfMm0CRrgq0UxFtBfBdArUMXSFkU30rtExbg6dlVFJCufw6UsCESm/QBSwlOyYKRdpsfVARcAw5G5OG0iX/22n+tYmCcWpmOJLJZaAmSynF1kwpBx3XDy40mFL6OMXjq
Replace your ssh key with a placeholder like `Add Your SSH Key`

2023-04-04 08:10 UTC, mohamedamer453 commented on cypress/e2e/vm_test.cy.js
> +      }
- Add the same flow to retrieve ssh key from `~/.ssh/id_rsa.pub` ([reference](https://github.com/threefoldtech/grid3_client_ts/blob/development/tests/client_loader.ts#L12) from grid3_client_ts)
- The if condition should also check if the mnemonics is empty 
```
(this.credentials.Mnemonics == "Add your Mnemonics" || this.credentials.Mnemonics == "" ) 
```

2023-04-04 08:10 UTC, mohamedamer453 commented on cypress/e2e/vm_test.cy.js
> +    profileManager.ActivateProfileManager(this.credentials.Mnemonics, this.credentials.SSH_KEY);
In the step for activating the profile manager, when the twin doesn't have a ssh key saved on the chain the test will fail because it doesn't wait for the key to be added and closes the profile manager right after.

[Screencast from 04-04-23 09:46:59.webm](https://user-images.githubusercontent.com/101194226/229724866-33f06ade-5c25-48aa-b264-db9bf5e36cb5.webm)

2023-04-04 15:26 UTC, A-Harby commented
https://github.com/threefoldtech/grid_weblets/actions/runs/4609463506/jobs/8146624969

2023-04-05 08:46 UTC, mohamedamer453 commented on cypress/e2e/vm_test.cy.js
> +    profileManager.ActivateProfileManager(this.credentials.Mnemonics, this.credentials.SSH_KEY);
Same issue is still present.

When you add the mnemonics of a twin that doesn't have a stored ssh key it gets added but the test doesn't wait for it until it gets stored on the chain. so a wait should be added in this section to wait and verify that the key was successfully added before closing the profile manager.

[Screencast from 05-04-23 10:42:08.webm](https://user-images.githubusercontent.com/101194226/230029682-0a89bd97-2a38-499f-a2f7-5cdc4e455218.webm)

2023-04-05 08:47 UTC, mohamedamer453 requested changes
`baseUrl` still points to qanet playground

2023-04-06 09:18 UTC, A-Harby commented
> `baseUrl` still points to qanet playground

Fixed
https://github.com/threefoldtech/grid_weblets/actions/runs/4627287459/jobs/8185027970

2023-04-10 11:02 UTC, mohamedamer453 approved these changes
lgtm the ssh section was fixed and the workflow was updated to run locally instead of on qanet.

2023-04-10 12:28 UTC, merged