update peertube default specs
threefoldtech/grid_weblets pull request #312
Opened 2021-12-21 11:24 UTC by Omarabdul3ziz

### Description

Update the defautl specs of peertube weblets to be:
- 200 GB disk
- 2 GB RAM
- 2 cores
- 4 GB rootfs

### Related Issues
#135 

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2021-12-21 11:27 UTC, abom requested changes
I think we need to make sure we have both "data" and "database" are persisted (can be on the same disk)

2021-12-21 13:45 UTC, ashraffouda commented
> I think we need to make sure that "data" and "database" are persisted (can be on the same disk), also, as it's now a single VM, we need to show these options to the user, that's what #135 is all about.

@abom to make this persistent this requires qsfs which is not ready atm, so we can skip this and we will add a note in the docs that data are not persistent atm and will be supperted in later version

2021-12-21 14:00 UTC, abom commented
Yes, we can mention this in the docs that videos are persistent but DB is not?

2021-12-22 11:33 UTC, abom approved these changes

2021-12-22 11:34 UTC, merged