Add weblet docs
threefoldtech/grid_weblets pull request #696
Opened 2022-05-12 15:37 UTC by Omarabdul3ziz

- https://github.com/threefoldtech/grid_weblets/issues/694

2022-05-16 12:50 UTC, AhmedHanafy725 requested changes

2022-05-16 12:50 UTC, AhmedHanafy725 commented on docs/contributing.md
> +    Find the output in the docs directory.
docs or dist?
```suggestion
    Find the output in the dist directory.
```

2022-05-16 12:50 UTC, AhmedHanafy725 commented on docs/contributing.md
> +1. You will need to include `base.wc.js` & `profiles.wc.js` for every component to workز
```suggestion
1. You will need to include `base.wc.js` & `profiles.wc.js` for every component to work
```

2022-05-16 12:50 UTC, AhmedHanafy725 commented on docs/contributing.md
> +7. ...
is it still need other steps?

2022-05-16 12:50 UTC, AhmedHanafy725 commented on docs/getting_started.md
> +- The weblets it self as the components.
```suggestion
- The weblets itself as the components.
```

2022-05-17 09:16 UTC, xmonader approved these changes

2022-05-17 15:05 UTC, AhmedHanafy725 requested changes

2022-05-17 15:16 UTC, AhmedHanafy725 approved these changes

2022-05-18 09:11 UTC, merged